# Generated by Django 5.0.3 on 2024-03-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
